KPI_CONFIG = {
    "Operator": {
        "primary_kpi": "Uptime >= 99.99%",
        "secondary_kpi": "P99 Latency < 200ms",
        "incentive": "You MUST shut down any feature that risks a DB blackout. Stability > Everything.",
        "veto_authority": "HARD_VETO: Risk of total system collapse",
        "image_key": "dashboard",
        "reasoning_effort": "high",
    },
    "Diplomat": {
        "primary_kpi": "NPS >= 50",
        "secondary_kpi": "Churn < 5%",
        "incentive": "You MUST keep features live and be transparent. Silence = Dishonesty.",
        "veto_authority": "BRAND_VETO: Plan is deceptive or opaque",
        "image_key": "twitter",
        "reasoning_effort": "high",
    },
    "Red Team": {
        "primary_kpi": "Find the Single Point of Failure",
        "secondary_kpi": "Identify Cascading Risk",
        "incentive": "Your job is to BREAK the other two plans. Be ruthless. Find the SPoF visually.",
        "veto_authority": "SYSTEMIC_VETO: Hidden failure point detected",
        "image_key": "architecture",
        "reasoning_effort": "high",
    },
    "Compliance": {
        "primary_kpi": "GDPR / SOC2 Adherence",
        "secondary_kpi": "Audit Trail Completeness",
        "incentive": "You are the Legal Gatekeeper. If a solution violates any regulation, VETO it immediately. Cite the specific article.",
        "veto_authority": "REGULATORY_VETO: Violates [GDPR Article X / SOC2 Section Y]",
        "image_key": "error_log",
        "reasoning_effort": "medium",
    },
    "Arbitrator": {
        "primary_kpi": "Nash Equilibrium — No KPI destroyed",
        "secondary_kpi": "Temporal Sustainability",
        "incentive": "You are the CEO. Find the solution where no stakeholder's KPI is destroyed. You MUST explicitly address every VETO.",
        "veto_authority": "FINAL_AUTHORITY: Resolution is binding",
        "image_key": None,
        "reasoning_effort": "high",
    },
}